import { permissionKey } from "./permissions";

/**
 * Initial role catalog (seeded as data — see prisma/seed.ts). These constants exist
 * so application code can reference ROLES.SUPER_ADMIN instead of a raw string; the
 * database remains the source of truth and new roles can be added without touching code.
 */
export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  BRANCH_MANAGER: "BRANCH_MANAGER",
  FRONT_DESK: "FRONT_DESK",
  CASHIER: "CASHIER",
  KITCHEN_MANAGER: "KITCHEN_MANAGER",
  KITCHEN_STAFF: "KITCHEN_STAFF",
  RIDER: "RIDER",
  FINANCE: "FINANCE",
  MARKETING: "MARKETING",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

const p = permissionKey;

/**
 * Default permission grants per role, used only for seeding. SUPER_ADMIN is granted
 * every permission in the catalog programmatically (see seed.ts) rather than listed here,
 * so it never drifts out of sync as new permissions are added.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<Exclude<RoleName, "SUPER_ADMIN">, string[]> = {
  [ROLES.ADMIN]: [
    p("branches", "read"),
    p("branches", "update"),
    p("users", "read"),
    p("users", "create"),
    p("users", "update"),
    p("roles", "read"),
    p("roles", "assign"),
    p("orders", "read"),
    p("orders", "create"),
    p("orders", "update"),
    p("orders", "cancel"),
    p("orders", "refund"),
    p("products", "read"),
    p("products", "create"),
    p("products", "update"),
    p("categories", "read"),
    p("categories", "create"),
    p("categories", "update"),
    p("inventory", "read"),
    p("inventory", "adjust"),
    p("inventory", "transfer"),
    p("recipes", "read"),
    p("recipes", "update"),
    p("suppliers", "read"),
    p("suppliers", "create"),
    p("suppliers", "update"),
    p("purchase_orders", "read"),
    p("purchase_orders", "create"),
    p("purchase_orders", "update"),
    p("kitchen", "read"),
    p("delivery", "read"),
    p("delivery", "update"),
    p("delivery", "assign"),
    p("riders", "read"),
    p("riders", "create"),
    p("riders", "update"),
    p("payments", "read"),
    p("payments", "create"),
    p("payments", "refund"),
    p("promotions", "read"),
    p("promotions", "create"),
    p("promotions", "update"),
    p("marketing", "read"),
    p("loyalty", "read"),
    p("notifications", "read"),
    p("analytics", "read"),
    p("analytics", "export"),
    p("audit", "read"),
    p("customers", "read"),
    p("customers", "create"),
    p("customers", "update"),
    p("support", "read"),
    p("support", "update"),
    p("reviews", "read"),
    p("reviews", "moderate"),
  ],
  [ROLES.BRANCH_MANAGER]: [
    p("branches", "read"),
    p("users", "read"),
    p("orders", "read"),
    p("orders", "create"),
    p("orders", "update"),
    p("orders", "cancel"),
    p("products", "read"),
    p("categories", "read"),
    p("inventory", "read"),
    p("inventory", "adjust"),
    p("inventory", "transfer"),
    p("recipes", "read"),
    p("recipes", "update"),
    p("suppliers", "read"),
    p("purchase_orders", "read"),
    p("purchase_orders", "create"),
    p("purchase_orders", "update"),
    p("kitchen", "read"),
    p("delivery", "read"),
    p("delivery", "update"),
    p("delivery", "assign"),
    p("riders", "read"),
    p("riders", "create"),
    p("riders", "update"),
    p("payments", "read"),
    p("payments", "create"),
    p("promotions", "read"),
    p("analytics", "read"),
    p("customers", "read"),
    p("support", "read"),
    p("reviews", "read"),
  ],
  [ROLES.FRONT_DESK]: [
    p("orders", "read"),
    p("orders", "create"),
    p("orders", "update"),
    p("products", "read"),
    p("categories", "read"),
    p("customers", "read"),
    p("customers", "create"),
    p("payments", "read"),
    p("payments", "create"),
    p("promotions", "read"),
    p("delivery", "read"),
    p("delivery", "update"),
    p("delivery", "assign"),
    p("riders", "read"),
  ],
  [ROLES.CASHIER]: [
    p("orders", "read"),
    p("orders", "create"),
    p("products", "read"),
    p("customers", "read"),
    p("payments", "read"),
    p("payments", "create"),
  ],
  [ROLES.KITCHEN_MANAGER]: [
    p("kitchen", "read"),
    p("kitchen", "update"),
    p("orders", "read"),
    p("inventory", "read"),
  ],
  [ROLES.KITCHEN_STAFF]: [p("kitchen", "read"), p("kitchen", "update"), p("orders", "read")],
  [ROLES.RIDER]: [p("delivery", "read"), p("delivery", "update"), p("orders", "read")],
  [ROLES.FINANCE]: [
    p("payments", "read"),
    p("payments", "refund"),
    p("orders", "read"),
    p("orders", "refund"),
    p("analytics", "read"),
    p("analytics", "export"),
    p("audit", "read"),
  ],
  [ROLES.MARKETING]: [
    p("marketing", "read"),
    p("marketing", "create"),
    p("marketing", "update"),
    p("marketing", "delete"),
    p("promotions", "read"),
    p("promotions", "create"),
    p("promotions", "update"),
    p("promotions", "delete"),
    p("loyalty", "read"),
    p("loyalty", "update"),
    p("analytics", "read"),
    p("customers", "read"),
  ],
  [ROLES.CUSTOMER_SUPPORT]: [
    p("support", "read"),
    p("support", "update"),
    p("orders", "read"),
    p("orders", "refund"),
    p("customers", "read"),
    p("customers", "update"),
    p("reviews", "read"),
    p("reviews", "moderate"),
    p("notifications", "read"),
  ],
};
