-- Human-friendly sequential purchase order numbers ("PO-1000", "PO-1001",
-- ...), generated by po-number.service.ts via nextval(). Started at 1000 to
-- mirror order_number_seq's convention.
CREATE SEQUENCE "po_number_seq" START WITH 1000 INCREMENT BY 1;
